In [3]:
import numpy as np

In [4]:
def startA (n):
	A = np.ones((n, n))
	for i in range(n):
		for j in range(n):
			A[i][j] = 10
	for i in range(n):
		A[0, i] = 100
		A[1, i] = 100

	Anew = A.copy()

	return A, Anew

In [5]:
startA(2)

(array([[100., 100.],
        [100., 100.]]), array([[100., 100.],
        [100., 100.]]))

In [20]:
A = np.zeros((4,4))

In [62]:
A

array([[100., 100.,   2.,   3.],
       [100., 100.,   2.,   3.],
       [  2.,   2.,   2.,   3.],
       [  1.,   1.,   2.,   3.]])

In [63]:
A.fill(1)

In [64]:
A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
A[0] = 100

In [36]:
A[1] = 100

In [37]:
A[2] = 2

In [38]:
A[:,3]=3
A[:,2]=2

In [39]:
A

array([[100., 100.,   2.,   3.],
       [100., 100.,   2.,   3.],
       [  2.,   2.,   2.,   3.],
       [  1.,   1.,   2.,   3.]])

In [68]:
def startA (n) :
    
    A = np.zeros((n,n))
    A.fill(10)
    A[0] = 100
    A[1] = 100
    
    Anew = A.copy()
    
    return A, Anew

In [69]:
B, Bnew = startA(5)

In [71]:
Bnew

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [ 10.,  10.,  10.,  10.,  10.],
       [ 10.,  10.,  10.,  10.,  10.],
       [ 10.,  10.,  10.,  10.,  10.]])

In [51]:
A[:-2,1:-1]

array([[100.,   2.],
       [100.,   2.]])

In [52]:
A[2:,1:-1]

array([[2., 2.],
       [1., 2.]])

In [53]:
A[1:-1,:-2]

array([[100., 100.],
       [  2.,   2.]])

In [54]:
A[1:-1,2:]

array([[2., 3.],
       [2., 3.]])

In [55]:
A[:-2,1:-1] + A[2:,1:-1] + A[1:-1,:-2] + A[1:-1,2:]

array([[204., 107.],
       [105.,   9.]])

In [57]:
Anew = A.copy()

In [58]:
Anew[1:-1,1:-1] = A[:-2,1:-1] + A[2:,1:-1] + A[1:-1,:-2] + A[1:-1,2:]

In [73]:
def makeMV(Anew, A):
	Anew[1:-1,1:-1] = A[:-2,1:-1] + A[2:,1:-1] + A[1:-1,:-2] + A[1:-1,2:]

In [74]:
makeMV(Bnew, B)

In [75]:
Bnew

array([[100., 100., 100., 100., 100.],
       [100., 310., 310., 310., 100.],
       [ 10., 130., 130., 130.,  10.],
       [ 10.,  40.,  40.,  40.,  10.],
       [ 10.,  10.,  10.,  10.,  10.]])

In [76]:
np.max(np.abs(Bnew) - np.abs(B))

210.0

In [77]:
def startA (n) :
    
    A = np.zeros((n,n))
    A.fill(10)
    A[0] = 100
    A[1] = 100
    
    Anew = A.copy()
    
    return A, Anew

def makeMV(Anew, A):
	Anew[1:-1,1:-1] = 0.25*(A[:-2,1:-1] + A[2:,1:-1] + A[1:-1,:-2] + A[1:-1,2:])

def error(A,Anew):
	return np.max(np.abs(Anew[1:-1,1:-1]) - np.abs(A[1:-1,1:-1]))

def copy(A, Anew, n):
	A = Anew.copy()

In [78]:
n = 100

A, Anew = startA(n)

In [89]:
A

array([[100., 100., 100., ..., 100., 100., 100.],
       [100., 100., 100., ..., 100., 100., 100.],
       [ 10.,  10.,  10., ...,  10.,  10.,  10.],
       ...,
       [ 10.,  10.,  10., ...,  10.,  10.,  10.],
       [ 10.,  10.,  10., ...,  10.,  10.,  10.],
       [ 10.,  10.,  10., ...,  10.,  10.,  10.]])

In [81]:
makeMV(Anew, A)

In [84]:
err = error(A, Anew)

In [86]:
Anew

array([[100. , 100. , 100. , ..., 100. , 100. , 100. ],
       [100. ,  77.5,  77.5, ...,  77.5,  77.5, 100. ],
       [ 10. ,  32.5,  32.5, ...,  32.5,  32.5,  10. ],
       ...,
       [ 10. ,  10. ,  10. , ...,  10. ,  10. ,  10. ],
       [ 10. ,  10. ,  10. , ...,  10. ,  10. ,  10. ],
       [ 10. ,  10. ,  10. , ...,  10. ,  10. ,  10. ]])

In [90]:
copy(A, Anew, n)

In [91]:
A

array([[100., 100., 100., ..., 100., 100., 100.],
       [100., 100., 100., ..., 100., 100., 100.],
       [ 10.,  10.,  10., ...,  10.,  10.,  10.],
       ...,
       [ 10.,  10.,  10., ...,  10.,  10.,  10.],
       [ 10.,  10.,  10., ...,  10.,  10.,  10.],
       [ 10.,  10.,  10., ...,  10.,  10.,  10.]])